language: python
python:
    - 3.8
notifications:
    email: false
install:
    - "pip install -r tests/requirements.txt"
jobs:
  include:
    - stage: format
      script: ./test_format.sh
cache: pip
