language: python
python:
    - 3.7
notifications:
    email: false
# install:
    # - "pip install -r requirements.txt"
    # - "pip install -r tests/requirements.txt"
jobs:
  include:
    # - stage: test
    #   script: ./test_robot.sh
    - stage: format
      script: ./test_format.sh
cache: pip
